# Non-personalised methods in Python

<h1>Table of Contents<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#Introduction-to-the-Data-from-A-Movie-Recommender-System" data-toc-modified-id="Introduction-to-the-Data-from-A-Movie-Recommender-System-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>Introduction to the Data from A Movie Recommender System</a></span></li><li><span><a href="#Ratings-and-User-Info" data-toc-modified-id="Ratings-and-User-Info-2"><span class="toc-item-num">2&nbsp;&nbsp;</span>Ratings and User Info</a></span><ul class="toc-item"><li><span><a href="#u.data" data-toc-modified-id="u.data-2.1"><span class="toc-item-num">2.1&nbsp;&nbsp;</span>u.data</a></span></li><li><span><a href="#u.info" data-toc-modified-id="u.info-2.2"><span class="toc-item-num">2.2&nbsp;&nbsp;</span>u.info</a></span></li><li><span><a href="#u.item" data-toc-modified-id="u.item-2.3"><span class="toc-item-num">2.3&nbsp;&nbsp;</span>u.item</a></span></li><li><span><a href="#u.genre" data-toc-modified-id="u.genre-2.4"><span class="toc-item-num">2.4&nbsp;&nbsp;</span>u.genre</a></span></li><li><span><a href="#u.user" data-toc-modified-id="u.user-2.5"><span class="toc-item-num">2.5&nbsp;&nbsp;</span>u.user</a></span></li><li><span><a href="#u.occupation" data-toc-modified-id="u.occupation-2.6"><span class="toc-item-num">2.6&nbsp;&nbsp;</span>u.occupation</a></span></li></ul></li><li><span><a href="#Practice" data-toc-modified-id="Practice-3"><span class="toc-item-num">3&nbsp;&nbsp;</span>Practice</a></span><ul class="toc-item"><li><span><a href="#Load-packages" data-toc-modified-id="Load-packages-3.1"><span class="toc-item-num">3.1&nbsp;&nbsp;</span>Load packages</a></span></li><li><span><a href="#explore-the-data-directory" data-toc-modified-id="explore-the-data-directory-3.2"><span class="toc-item-num">3.2&nbsp;&nbsp;</span>explore the data directory</a></span></li><li><span><a href="#Load-the-rating-data-to-pandas-dataframe" data-toc-modified-id="Load-the-rating-data-to-pandas-dataframe-3.3"><span class="toc-item-num">3.3&nbsp;&nbsp;</span>Load the rating data to pandas dataframe</a></span></li><li><span><a href="#Load-the-item-data" data-toc-modified-id="Load-the-item-data-3.4"><span class="toc-item-num">3.4&nbsp;&nbsp;</span>Load the item data</a></span></li><li><span><a href="#Convert-data-into-user-item-rating-matrix-and-user-item-binary-rating-matrix" data-toc-modified-id="Convert-data-into-user-item-rating-matrix-and-user-item-binary-rating-matrix-3.5"><span class="toc-item-num">3.5&nbsp;&nbsp;</span>Convert data into user-item rating matrix and user-item binary rating matrix</a></span><ul class="toc-item"><li><span><a href="#check-the-number-of-users-and-items" data-toc-modified-id="check-the-number-of-users-and-items-3.5.1"><span class="toc-item-num">3.5.1&nbsp;&nbsp;</span>check the number of users and items</a></span></li><li><span><a href="#Construct-the-user-time-rating-matrix" data-toc-modified-id="Construct-the-user-time-rating-matrix-3.5.2"><span class="toc-item-num">3.5.2&nbsp;&nbsp;</span>Construct the user-time rating matrix</a></span></li></ul></li><li><span><a href="#Calculate-movie’s-popularity/average-rating" data-toc-modified-id="Calculate-movie’s-popularity/average-rating-3.6"><span class="toc-item-num">3.6&nbsp;&nbsp;</span>Calculate movie’s popularity/average rating</a></span></li><li><span><a href="#TopPop" data-toc-modified-id="TopPop-3.7"><span class="toc-item-num">3.7&nbsp;&nbsp;</span>TopPop</a></span><ul class="toc-item"><li><span><a href="#Specify-the-number-of-recommended-items" data-toc-modified-id="Specify-the-number-of-recommended-items-3.7.1"><span class="toc-item-num">3.7.1&nbsp;&nbsp;</span>Specify the number of recommended items</a></span></li><li><span><a href="#Mask-the-'rated'-items-for-the-active-user" data-toc-modified-id="Mask-the-'rated'-items-for-the-active-user-3.7.2"><span class="toc-item-num">3.7.2&nbsp;&nbsp;</span>Mask the 'rated' items for the active user</a></span></li><li><span><a href="#Make-a-copy-of-itemRateNum" data-toc-modified-id="Make-a-copy-of-itemRateNum-3.7.3"><span class="toc-item-num">3.7.3&nbsp;&nbsp;</span>Make a copy of itemRateNum</a></span></li><li><span><a href="#Exclude-reated-items-from-recommendation-by-setting-their-popularity-to-0" data-toc-modified-id="Exclude-reated-items-from-recommendation-by-setting-their-popularity-to-0-3.7.4"><span class="toc-item-num">3.7.4&nbsp;&nbsp;</span>Exclude reated items from recommendation by setting their popularity to 0</a></span></li><li><span><a href="#Sort-Movies-by-their-populairty-in-descending-order." data-toc-modified-id="Sort-Movies-by-their-populairty-in-descending-order.-3.7.5"><span class="toc-item-num">3.7.5&nbsp;&nbsp;</span>Sort Movies by their populairty in descending order.</a></span></li><li><span><a href="#Find-the-top_n-items-and-print" data-toc-modified-id="Find-the-top_n-items-and-print-3.7.6"><span class="toc-item-num">3.7.6&nbsp;&nbsp;</span>Find the top_n items and print</a></span></li></ul></li></ul></li><li><span><a href="#MovieAvg" data-toc-modified-id="MovieAvg-4"><span class="toc-item-num">4&nbsp;&nbsp;</span>MovieAvg</a></span><ul class="toc-item"><li><ul class="toc-item"><li><span><a href="#Specify-the-number-of-recommended-items" data-toc-modified-id="Specify-the-number-of-recommended-items-4.0.1"><span class="toc-item-num">4.0.1&nbsp;&nbsp;</span>Specify the number of recommended items</a></span></li><li><span><a href="#Mask-the-'rated'-items-for-the-active-user" data-toc-modified-id="Mask-the-'rated'-items-for-the-active-user-4.0.2"><span class="toc-item-num">4.0.2&nbsp;&nbsp;</span>Mask the 'rated' items for the active user</a></span></li><li><span><a href="#Make-a-copy-of-itemRateAvg" data-toc-modified-id="Make-a-copy-of-itemRateAvg-4.0.3"><span class="toc-item-num">4.0.3&nbsp;&nbsp;</span>Make a copy of itemRateAvg</a></span></li><li><span><a href="#Exclude-reated-items-from-recommendation-by-setting-their-popularity-to-0" data-toc-modified-id="Exclude-reated-items-from-recommendation-by-setting-their-popularity-to-0-4.0.4"><span class="toc-item-num">4.0.4&nbsp;&nbsp;</span>Exclude reated items from recommendation by setting their popularity to 0</a></span></li><li><span><a href="#Sort-Movies-by-their-populairty-in-descending-order." data-toc-modified-id="Sort-Movies-by-their-populairty-in-descending-order.-4.0.5"><span class="toc-item-num">4.0.5&nbsp;&nbsp;</span>Sort Movies by their populairty in descending order.</a></span></li><li><span><a href="#Find-the-top_n-items-and-print" data-toc-modified-id="Find-the-top_n-items-and-print-4.0.6"><span class="toc-item-num">4.0.6&nbsp;&nbsp;</span>Find the top_n items and print</a></span></li></ul></li></ul></li></ul></div>

## Introduction to the Data from A Movie Recommender System

MovieLens (100k)
MovieLens is a data set which consists of 100,000 ratings (1-5) from 943 users on 1682 movies.

Each user has rated at least 20 movies.

Simple demographic information for the users includes age, gender, occupation, zip code.

The data was collected through the MovieLens web site (movielens.umn.edu) during the seven-month period from September 19th, 1997 through April 22nd, 1998.

This data has been cleaned up and users who had less than 20 ratings or did not have complete demographic information were removed from this data set.

## Ratings and User Info
Here are the member variables on u dataset.

### u.data

The full `u` data set, 100000 ratings by 943 users on 1682 items.

Each user has rated at least 20 movies. 

Users and items are numbered consecutively from 1. 

The data is randomly ordered.

This is a tab separated list of

- user id | item id | rating | timestamp

- The time stamps are unix seconds since 1/1/1970 UTC  

### u.info

The number of users, items, and ratings in the u data set.

### u.item

Information about the items (movies); this is a tab separated list of

              movie id | movie title | release date | video release date |

              IMDb URL | unknown | Action | Adventure | Animation |

              Children's | Comedy | Crime | Documentary | Drama | Fantasy |

              Film-Noir | Horror | Musical | Mystery | Romance | Sci-Fi |

              Thriller | War | Western |

The last 19 fields are the genres, a 1 indicates the movie is of that genre, a 0 indicates it is not; movies can be in several genres at once.

### u.genre

 

A list of the genres.

The movie ids are the ones used in the u.data data set.

### u.user

Demographic information about the users;

this is a tab separated list of

              user id | age | gender | occupation | zip code

The user ids are the ones used in the u.data data set.

### u.occupation
A list of the occupations.

## Practice

### Load packages

In [1]:
import numpy as np
import pandas as pd

### explore the data directory

Move into the data directory

In [2]:
cd ml-100k/

/Users/jayarajkumarayyappan/Pythonworks/ml-100k

List the files in the ml-100k folder

In [3]:
ls

README        u.info        u1.test       u4.base       ua.test
allbut.pl*    u.item        u2.base       u4.test       ub.base
mku.sh*       u.occupation  u2.test       u5.base       ub.test
u.data        u.user        u3.base       u5.test
u.genre       u1.base       u3.test       ua.base

Print the first 10 lines in u.data:

In [4]:
!head u.data

196	242	3	881250949
186	302	3	891717742
22	377	1	878887116
244	51	2	880606923
166	346	1	886397596
298	474	4	884182806
115	265	2	881171488
253	465	5	891628467
305	451	3	886324817
6	86	3	883603013

### Load the rating data to pandas dataframe

In [5]:
names = ['user_id', 'item_id', 'rating', 'timestamp']
df = pd.read_csv('u.data', sep='\t', names=names)
df.head()

   user_id  item_id  rating  timestamp
0      196      242       3  881250949
1      186      302       3  891717742
2       22      377       1  878887116
3      244       51       2  880606923
4      166      346       1  886397596

### Load the item data

In [6]:
i_cols = ['movie id', 'movie title' ,'release date','video release date', 'IMDb URL', 'unknown', 'Action', 'Adventure',
 'Animation', 'Children\'s', 'Comedy', 'Crime', 'Documentary', 'Drama', 'Fantasy',
 'Film-Noir', 'Horror', 'Musical', 'Mystery', 'Romance', 'Sci-Fi', 'Thriller', 'War', 'Western']
items = pd.read_csv('u.item', sep='|', names=i_cols, encoding='latin-1')

items.head()

,movie id,movie title,release date,video release date,IMDb URL,unknown,Action,Adventure,Animation,Children's,...,Fantasy,Film-Noir,Horror,Musical,Mystery,Romance,Sci-Fi,Thriller,War,Western
0,1,Toy Story (1995),01-Jan-1995,NaN,http://us.imdb.com/M/title-exact?Toy%20Story%2...,0,0,0,1,1,...,0,0,0,0,0,0,0,0,0,0
1,2,GoldenEye (1995),01-Jan-1995,NaN,http://us.imdb.com/M/title-exact?GoldenEye%20(...,0,1,1,0,0,...,0,0,0,0,0,0,0,1,0,0
2,3,Four Rooms (1995),01-Jan-1995,NaN,http://us.imdb.com/M/title-exact?Four%20Rooms%...,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
3,4,Get Shorty (1995),01-Jan-1995,NaN,http://us.imdb.com/M/title-exact?Get%20Shorty%...,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,5,Copycat (1995),01-Jan-1995,NaN,http://us.imdb.com/M/title-exact?Copycat%20(1995),0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0

### Convert data into user-item rating matrix and user-item binary rating matrix

#### check the number of users and items

In [7]:
n_users = df.user_id.unique().shape[0]
n_items = df.item_id.unique().shape[0]
print(f"{n_users} users")
print(f"{n_items} items")

943 users
1682 items

#### Construct the user-time rating matrix

In [8]:
ratings = np.zeros((n_users, n_items))

In [9]:
ratingsNum = np.zeros((n_users, n_items))

In [10]:
for row in df.itertuples():
    ratings[row[1]-1, row[2]-1] = row[3]
    ratingsNum[row[1]-1, row[2]-1] = 1
print(ratings)
print(ratingsNum)

[[5. 3. 4. ... 0. 0. 0.]
 [4. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [5. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 5. 0. ... 0. 0. 0.]]
[[1. 1. 1. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [1. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]]

Watch the following video

In [11]:
%%HTML
<video width="100%" controls> 
    <source src="./matrix.mp4" type="video/mp4"> 
</video>

To better understand the codes in the video above, explore the diagram below.

![flowchart](flowchart.png)

### Calculate movie’s popularity/average rating

Calculate the popularity: the number of 'rated' times

In [12]:
itemRateNum = ratingsNum.sum(axis=0)
print(itemRateNum)

[452. 131.  90. ...   1.   1.   1.]

Calculate the total ratings obtained by each item

In [13]:
itemRateSum = ratings.sum(axis=0)
print(itemRateSum)

[1753.  420.  273. ...    2.    3.    3.]

Calculate the average rating for each item

In [14]:
itemRateAvg = itemRateSum/itemRateNum
print(itemRateAvg)

[3.87831858 3.20610687 3.03333333 ... 2.         3.         3.        ]

### TopPop

#### Specify the number of recommended items

In [15]:
top_n = 5

#### Mask the 'rated' items for the active user

In [16]:
activeUser = 0

In [17]:
mask_activeUser = ratings[activeUser, :] > 0

#### Make a copy of itemRateNum

In [18]:
itemRateNumCurrent = itemRateNum.copy()

#### Exclude reated items from recommendation by setting their popularity to 0

In [19]:
itemRateNumCurrent[mask_activeUser] = 0

#### Sort Movies by their populairty in descending order. 
The first one is the most popular one

In [20]:
itemSortInd = itemRateNumCurrent.argsort()[::-1]

#### Find the top_n items and print

In [21]:
top_ind = itemSortInd[:top_n]

In [22]:
items.iloc[top_ind,:][['movie id', 'movie title']]

     movie id                  movie title
293       294             Liar Liar (1997)
285       286  English Patient, The (1996)
287       288                Scream (1996)
299       300         Air Force One (1997)
312       313               Titanic (1997)

## MovieAvg

#### Specify the number of recommended items

In [23]:
top_n = 5

#### Mask the 'rated' items for the active user

In [24]:
activeUser = 0

In [25]:
mask_activeUser = ratings[activeUser, :] > 0

#### Make a copy of itemRateAvg

In [26]:
itemRateAvgCurrent = itemRateAvg.copy()

#### Exclude reated items from recommendation by setting their popularity to 0

In [27]:
itemRateAvgCurrent[mask_activeUser] = 0

#### Sort Movies by their populairty in descending order. 
The first one is the most popular one

In [28]:
itemSortInd = itemRateAvgCurrent.argsort()[::-1]

#### Find the top_n items and print

In [29]:
top_ind = itemSortInd[:top_n]

In [30]:
items.iloc[top_ind,:][['movie id', 'movie title']]

      movie id                                        movie title
1535      1536                               Aiqing wansui (1994)
1652      1653  Entertaining Angels: The Dorothy Day Story (1996)
1200      1201         Marlene Dietrich: Shadow and Light (1996)
1598      1599                      Someone Else's America (1995)
1121      1122                     They Made Me a Criminal (1939)